// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwaggerDemo;

namespace SwaggerDemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SwaggerDemo.Model.BUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("aclsId")
                        .HasColumnType("integer");

                    b.Property<string>("businessUnit")
                        .HasColumnType("text");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("aclsId");

                    b.ToTable("BUnit");
                });

            modelBuilder.Entity("SwaggerDemo.Model.BatchIds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BatchId");
                });

            modelBuilder.Entity("SwaggerDemo.Model.acl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<List<string>>("readGroups")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("readUsers")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("acl");
                });

            modelBuilder.Entity("SwaggerDemo.Model.attributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("key")
                        .HasColumnType("text");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BUnitId");

                    b.ToTable("attributes");
                });

            modelBuilder.Entity("SwaggerDemo.Model.files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BUnitId")
                        .HasColumnType("integer");

                    b.Property<int?>("attrId")
                        .HasColumnType("integer");

                    b.Property<int>("fileSize")
                        .HasColumnType("integer");

                    b.Property<string>("filename")
                        .HasColumnType("text");

                    b.Property<string>("hash")
                        .HasColumnType("text");

                    b.Property<string>("mimeType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BUnitId");

                    b.HasIndex("attrId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("SwaggerDemo.Model.BUnit", b =>
                {
                    b.HasOne("SwaggerDemo.Model.acl", "acls")
                        .WithMany()
                        .HasForeignKey("aclsId");

                    b.Navigation("acls");
                });

            modelBuilder.Entity("SwaggerDemo.Model.attributes", b =>
                {
                    b.HasOne("SwaggerDemo.Model.BUnit", null)
                        .WithMany("attr")
                        .HasForeignKey("BUnitId");
                });

            modelBuilder.Entity("SwaggerDemo.Model.files", b =>
                {
                    b.HasOne("SwaggerDemo.Model.BUnit", null)
                        .WithMany("file")
                        .HasForeignKey("BUnitId");

                    b.HasOne("SwaggerDemo.Model.attributes", "attr")
                        .WithMany()
                        .HasForeignKey("attrId");

                    b.Navigation("attr");
                });

            modelBuilder.Entity("SwaggerDemo.Model.BUnit", b =>
                {
                    b.Navigation("attr");

                    b.Navigation("file");
                });
#pragma warning restore 612, 618
        }
    }
}
